apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops-test
  labels:
    app: nginx-gitops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gitops-test
  template:
    metadata:
      labels:
        app: nginx-gitops-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops-test-service
  labels:
    app: nginx-gitops-test
spec:
  selector:
    app: nginx-gitops-test
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-gitops-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nginx-gitops-test.deploai.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-gitops-test-service
            port:
              number: 80
